# Generated by Django 5.0.3 on 2024-03-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('age_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'life',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('welfare_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('welfare_ori_id', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_child', models.IntegerField(blank=True, null=True)),
                ('welfare_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_crit', models.TextField(blank=True, null=True)),
                ('welfare_date', models.TextField(blank=True, null=True)),
                ('welfare_dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_female', models.BigIntegerField(blank=True, null=True)),
                ('welfare_group', models.BigIntegerField(blank=True, null=True)),
                ('welfare_howto', models.TextField(blank=True, null=True)),
                ('welfare_male', models.BigIntegerField(blank=True, null=True)),
                ('welfare_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_service_content', models.TextField(blank=True, null=True)),
                ('welfare_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_service_purpose', models.TextField(blank=True, null=True)),
                ('welfare_service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_similar_welfare', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_site_link', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_target_detail', models.TextField(blank=True, null=True)),
                ('welfare_view', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welfare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfare_similarwelfare',
            fields=[
                ('welfare_welfare_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'similarwelfare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarefamily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('family_id', models.IntegerField(blank=True, null=True)),
                ('welfare_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welfarefamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarelife',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('life_id', models.IntegerField(blank=True, null=True)),
                ('welfare_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welfarelife',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfaretarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('welfare_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welfaretarget',
                'managed': False,
            },
        ),
    ]
