spring:
  datasource:
    url: jdbc:mysql://REMOVED
    username: root
    password: REMOVED
    driver-class-name: com.mysql.cj.jdbc.Driver



web:
  cors:
    allowed-origins=*:

server:
  servlet:
    context-path: /api

